In [6]:
import pandas as pd
import numpy as np
import seaborn as sns
from collections import Counter
import collections
from scipy import stats
from sklearn.preprocessing import OneHotEncoder

In [ ]:
# 04262024
# Completed data set
# other (only 1)
# tax registry (all)
# deposit (only 1)
# debitcard
# static(all)

# person_1 (half way, did the basic filtering (num_groups))

In [7]:
path = r'csv_files/train/'

# Static

In [8]:
static_0_0 = pd.read_csv(path+'train_static_0_0.csv')
static_0_1 = pd.read_csv(path+'train_static_0_1.csv')

/var/folders/t2/f76wtzld0ds5dwmrb4tpvm5r0000gn/T/ipykernel_36653/3319092595.py:1: DtypeWarning: Columns (20,45,46,53,57,84,143,146,167) have mixed types. Specify dtype option on import or set low_memory=False.
  static_0_0 = pd.read_csv(path+'train_static_0_0.csv')
/var/folders/t2/f76wtzld0ds5dwmrb4tpvm5r0000gn/T/ipykernel_36653/3319092595.py:2: DtypeWarning: Columns (20,45,46,56,57,84,143,146,167) have mixed types. Specify dtype option on import or set low_memory=False.
  static_0_1 = pd.read_csv(path+'train_static_0_1.csv')

In [9]:
static_0_0 = static_0_0.sample(50000)

In [10]:
# keep which STATUS is To binary and K
# K is to regular dummy
# To binary to make the exist on 1 and 0 for na

In [11]:
variables = pd.read_excel('home credit variables.xlsx')
variables = variables[(variables['file'] == 'static')]
variables = variables[['Variable', 'Variable Type', 'STATUS','Fillna' ,'file']]


def data_process(variables,df_org):

    binary = variables[variables['STATUS']=='To binary']
    dummies = variables[variables['STATUS']=='K']
    delete = variables[variables['STATUS']=='D']

    df_org = df_org.drop(columns=list(delete['Variable']))

    dummies_data = df_org[list(dummies['Variable'])].copy()

    dummies_data = pd.get_dummies(dummies_data, dtype=float)

    df_org = df_org.drop(columns=list(dummies['Variable']))

    binary_data = df_org[list(binary['Variable'])].copy()

    for i in binary_data.columns:
        binary_data.loc[pd.isnull(binary_data[i]),i] = 0
        binary_data.loc[pd.isnull(binary_data[i])==False,i] = 0

    df_org = df_org.drop(columns=list(binary['Variable']))

    df = pd.concat([df_org,binary_data,dummies_data],axis = 1)
    
    # fillna
    fillmissing = variables[variables['Variable Type'] == 'N']
    
    
    for i in range(0,len(fillmissing)):
        fill = fillmissing.iloc[i]['Fillna']
        v = fillmissing.iloc[i]['Variable']
        if(fill == 0):
            df[v].fillna(0,inplace = True)
        elif(fill == 'avg'):
            df[v].fillna(df[v].mean(),inplace = True)
        
    
    
    
    return df

In [191]:
static_0_0

,case_id,actualdpdtolerance_344P,amtinstpaidbefduel24m_4187115A,annuity_780A,annuitynextmonth_57A,applicationcnt_361L,applications30d_658L,applicationscnt_1086L,applicationscnt_464L,applicationscnt_629L,...,lastst_736L_N,lastst_736L_P,lastst_736L_Q,lastst_736L_S,lastst_736L_T,paytype_783L_OTHER,paytype1st_925L_OTHER,twobodfilling_608L_BO,twobodfilling_608L_FO,typesuite_864L_AL
843802,1653624,0.0,1352.0599,4707.6000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0
219140,694188,0.0,0.0000,3832.8000,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0
537063,1346885,0.0,102923.7700,7988.0000,7361.4,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0
344220,819268,0.0,0.0000,1702.2001,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,1.0
605815,1415637,0.0,0.0000,5002.6000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
526156,1335978,0.0,36592.2460,6079.2000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0
713299,1523121,0.0,34915.4020,1411.0000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0
154003,629051,0.0,0.0000,1537.8000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,1.0
759206,1569028,0.0,9189.4000,1913.6000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0
441603,1251425,0.0,0.0000,1834.6000,2396.6,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0

In [12]:
static_0_0 = data_process(variables,static_0_0)

# Tax Registry

In [41]:
# Process Tax registry file
tax_file_list = ['a','b','c']

for t in tax_file_list:

    tax = pd.read_csv(path+f'train_tax_registry_{t}_1.csv')

    tmp = tax.groupby(['case_id']).agg({'num_group1':'max'}).reset_index()

    tax = tax.merge(tmp, on = ['case_id','num_group1'],how = 'right')
    
    tax.to_excel(f'tmp/train_tax_registry_{t}_1_cleaned.xlsx',index = False)

# Deposit

In [104]:
# Deposit

deposit = pd.read_csv(path+f'train_deposit_1.csv')


deposit['amount_416A'] = deposit['amount_416A'].fillna(0)

# mark the potential error
deposit['Flag'] = 0

# end date older than startdate
deposit.loc[deposit['contractenddate_991D'] < deposit['openingdate_313D'],'Flag'] = 1

deposit['record_changes_deposit'] = 1

deposit.loc[pd.isnull(deposit['contractenddate_991D']) == False,'contractenddate_991D'] = 1

deposit.loc[pd.isnull(deposit['contractenddate_991D']),'contractenddate_991D'] = 0

tmp = deposit.groupby(['case_id']).agg({'num_group1':'max','record_changes_deposit':'sum'}).reset_index()


deposit.drop(columns = ['record_changes_deposit'],inplace = True)

deposit = deposit.merge(tmp, on = ['case_id','num_group1'],how = 'right')

deposit.drop(columns = ['openingdate_313D'],inplace = True)

deposit.to_excel(f'tmp/deposit_cleaned.xlsx',index = False)

In [179]:
# train person 1
person_1 = pd.read_csv(path+f'train_person_1.csv')


person_1['birth_day'] = np.nan

condition = pd.notnull(person_1['birth_259D']) & pd.isnull(person_1['birthdate_87D'])

person_1.loc[condition,'birth_day'] = person_1.loc[condition,'birth_259D']

condition = pd.isnull(person_1['birth_259D']) & pd.notnull(person_1['birthdate_87D'])

person_1.loc[condition,'birth_day'] = person_1.loc[condition,'birthdate_87D']

condition = pd.notnull(person_1['birth_259D']) & pd.notnull(person_1['birthdate_87D'])

person_1.loc[condition,'birth_day'] = person_1.loc[condition,'birthdate_87D']

person_1.drop(columns = ['birth_259D', 'birthdate_87D'],inplace = True)


# a55475b1 should be as previous

person_1.replace('a55475b1', np.nan, inplace=True)

person_1.sort_values(by=['case_id', 'num_group1'],inplace = True)

person_1.fillna(method = 'ffill',inplace = True)


tmp = person_1.groupby(['case_id']).agg({'num_group1':'max'}).reset_index()

person_1 = person_1.merge(tmp, on = ['case_id','num_group1'],how = 'right')

/var/folders/t2/f76wtzld0ds5dwmrb4tpvm5r0000gn/T/ipykernel_36653/4294586668.py:2: DtypeWarning: Columns (16) have mixed types. Specify dtype option on import or set low_memory=False.
  person_1 = pd.read_csv(path+f'train_person_1.csv')

# Other

In [187]:
# other 
other = pd.read_csv(path+f'train_other_1.csv')

tmp = other.groupby(['case_id']).agg({'num_group1':'max'}).reset_index()

other = other.merge(tmp, on = ['case_id','num_group1'],how = 'right')

# debitcard

In [70]:
# train_debitcard
debitcard = pd.read_csv(path+f'train_debitcard_1.csv')

# count change times
debitcard['records_changes'] = 1



tmp = debitcard.groupby(['case_id']).agg({'num_group1':'max','records_changes':'sum'}).reset_index()

debitcard.drop(columns = ['records_changes'],inplace = True)

debitcard = debitcard.merge(tmp, on = ['case_id','num_group1'],how = 'right')

# fill na with -1

debitcard = debitcard.fillna(-1)

debitcard.to_excel('tmp/debitcard_cleaned.xlsx',index = False)